

development:
  adapter: mysql2
  database: publify_dev
  username: root
  password: 
  host: localhost
  encoding: utf8 
  port: 3306 
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: publify_test
  username: root
  password: 
  host: localhost
  port: 3306 
  encoding: utf8 
  pool: 5
  timeout: 5000  

production:
  adapter: mysql2
  database: publify
  username: root
  password: or14g6914r
  host: 54.72.214.184
  encoding: utf8
  port: 3306
  pool: 5
  timeout: 5000
