  username: root
  password: g61x2bhps9
  adapter: mysql2
  encoding: utf8
  password: 
  host: 54.77.182.117
  port: 3306 


development:
  database: publify_dev
  <<: *login

test:
  database: publify_tests
  <<: *login

production:
  database: publify
  <<: *login
