login: &login
  adapter: mysql2
  host: 54.72.222.192
  username: root
  password:


development:
  database: publify_dev
  <<: *login

test:
  database: publify_tests
  <<: *login

production:
  database: publify
  <<: *login
