default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "smtp.sendgrid.net"
      port: 587
      authentication: :plain
      domain: "heroku.com"
      user_name: USERNAME
      password: PASSWORD